apiVersion: gitops.promotioncontroller.prototype/v1alpha1
kind: Environment
metadata:
  name: dev
spec:
  source:
    url: https://github.com/thomasstxyz/example-kustomize-overlay-dev
    ref:
      branch: main
    path: ./envs/dev
---
apiVersion: gitops.promotioncontroller.prototype/v1alpha1
kind: Environment
metadata:
  name: prod
spec:
  source:
    url: https://github.com/thomasstxyz/example-kustomize-overlay-prod
    ref:
      branch: main
    path: ./envs/prod
    # Get a personal access token from GitHub, and store it in a secret.
    # Create the secret with the following command:
    # $ kubectl create secret generic github-token --from-literal=token="github_pat***"
    secretRef:
      name: github-token
    # spec.source.provider is required if you want to raise a pull request on promotion.
    provider: github
