apiVersion: gitops.promotioncontroller.prototype/v1alpha1
kind: Environment
metadata:
  labels:
    app.kubernetes.io/name: environment
    app.kubernetes.io/instance: environment-sample
    app.kubernetes.io/part-of: promotion-controller
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/created-by: promotion-controller
  name: environment-sample
spec:
  # TODO(user): Add fields here
