apiVersion: gitops.promotioncontroller.prototype/v1alpha1
kind: Promotion
metadata:
  name: from-dev-to-prod
spec:
  copy:
  - source: app-version
    target: app-version
  - source: ./app-version/kustomization.yaml
    target: ./app-version/
  - source: app-version/kustomization.yaml
    target: app-version
  - source: app-version/kustomization.yaml
    target: app-version/kustomization.yaml
  sourceEnvironment: dev
  targetEnvironment: prod
  strategy:
    pullRequest: true
