apiVersion: gitops.promotioncontroller.prototype/v1alpha1
kind: Promotion
metadata:
  name: promotion-sample-dev-to-prod-1
spec:
  copy:
  - source: app-version
    target: app-version
  - source: ./app-version/kustomization.yaml
    target: ./app-version/
  - source: app-version/kustomization.yaml
    target: app-version
  - source: app-version/kustomization.yaml
    target: app-version/kustomization.yaml
  sourceEnvironment: environment-sample-dev
  targetEnvironment: environment-sample-prod
  strategy:
    pullRequest:
      title: "Promotion from dev to prod"
      body: "Promotion from dev to prod"
      provider: github
